export const BEGIN_GET_LIST_BLOG = 'BEGIN_GET_LIST_BLOG';
export const GET_LIST_BLOG_SUCCESS = 'GET_LIST_BLOG_SUCCESS';
export const BEGIN_REFRESH_NEW_FEED = "BEGIN_REFRESH_NEW_FEED";
export const REFRESH_NEW_FEED_SUCCESS = "REFRESH_NEW_FEED_SUCCESS";
export const REFRESH_NEW_FEED_ERROR = "REFRESH_NEW_FEED_ERROR";
export const BEGIN_GET_MORE_LIST_BLOG = 'BEGIN_GET_MORE_LIST_BLOG';
export const GET_MORE_LIST_BLOG_SUCCESS = 'GET_MORE_LIST_BLOG_SUCCESS';

export const BEGIN_GET_BLOG = 'BEGIN_GET_BLOG';
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';

// GET LIST BOOK
export const BEGIN_GET_LIST_BOOK = "BEGIN_GET_LIST_BOOK";
export const GET_LIST_BOOK_SUCCESS = "GET_LIST_BOOK_SUCCESS";
export const BEGIN_GET_MORE_LIST_BOOK = "BEGIN_GET_MORE_LIST_BOOK";
export const GET_MORE_LIST_BOOK_SUCCESS = "GET_MORE_LIST_BOOK_SUCCESS";
export const BEGIN_GET_TYPE_BOOK = "BEGIN_GET_TYPE_BOOK";
export const GET_TYPE_BOOK_SUCCESS = "GET_TYPE_BOOK_SUCCESS";
